# 👥 IBM HR Analytics – Employee Attrition Analysis

This notebook explores employee attrition, compensation, job roles, satisfaction, experience, and workforce characteristics using Python.

## 1. Import Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

## 2. Load Dataset

In [6]:
# Update this path if your CSV has a different name or location.
file_path = '/content/IBM HR Analytics Employee.csv'
df = pd.read_csv(file_path)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

## 3. Data Understanding

In [7]:
print('Rows:', df.shape[0])
print('Columns:', df.shape[1])
display(df.head())
display(df.dtypes)

Rows: 1470
Columns: 35

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

## 4. Data Quality Checks

In [9]:
print('Missing values:')
display(df.isnull().sum().sort_values(ascending=False).head(10))
print('Duplicate rows:', df.duplicated().sum())

Missing values:

Age                 0
Attrition           0
BusinessTravel      0
DailyRate           0
Department          0
DistanceFromHome    0
Education           0
EducationField      0
EmployeeCount       0
EmployeeNumber      0
dtype: int64

Duplicate rows: 0

## 5. Overall Attrition Analysis

In [8]:
attrition_counts = df['Attrition'].value_counts()
attrition_rate = df['Attrition'].eq('Yes').mean() * 100
print(f'Overall attrition rate: {attrition_rate:.2f}%')
display(attrition_counts)

Overall attrition rate: 16.12%

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [ ]:
attrition_counts.plot(kind='bar', title='Employee Attrition')
plt.xlabel('Attrition')
plt.ylabel('Number of Employees')
plt.xticks(rotation=0)
plt.show()

## 6. Attrition by Department and Job Role

In [10]:
department_attrition = pd.crosstab(df['Department'], df['Attrition'], normalize='index') * 100
display(department_attrition)
jobrole_attrition = pd.crosstab(df['JobRole'], df['Attrition'], normalize='index') * 100
display(jobrole_attrition.sort_values('Yes', ascending=False))

Attrition                      No        Yes
Department
Human Resources         80.952381  19.047619
Research & Development  86.160250  13.839750
Sales                   79.372197  20.627803

Attrition                         No        Yes
JobRole
Sales Representative       60.240964  39.759036
Laboratory Technician      76.061776  23.938224
Human Resources            76.923077  23.076923
Sales Executive            82.515337  17.484663
Research Scientist         83.904110  16.095890
Manufacturing Director     93.103448   6.896552
Healthcare Representative  93.129771   6.870229
Manager                    95.098039   4.901961
Research Director          97.500000   2.500000

## 7. Overtime and Attrition

In [11]:
overtime_attrition = pd.crosstab(df['OverTime'], df['Attrition'], normalize='index') * 100
display(overtime_attrition)

Attrition         No        Yes
OverTime
No         89.563567  10.436433
Yes        69.471154  30.528846

## 8. Compensation Analysis

In [12]:
print('Average Monthly Income:', round(df['MonthlyIncome'].mean(), 2))
income_by_role = df.groupby('JobRole')['MonthlyIncome'].agg(['count', 'mean', 'median']).sort_values('mean', ascending=False)
display(income_by_role)

Average Monthly Income: 6502.93

                           count          mean   median
JobRole
Manager                      102  17181.676471  17454.5
Research Director             80  16033.550000  16510.0
Healthcare Representative    131   7528.763359   6811.0
Manufacturing Director       145   7295.137931   6447.0
Sales Executive              326   6924.279141   6231.0
Human Resources               52   4235.750000   3093.0
Research Scientist           292   3239.972603   2887.5
Laboratory Technician        259   3237.169884   2886.0
Sales Representative          83   2626.000000   2579.0

## 9. Employee Satisfaction Analysis

In [13]:
satisfaction_columns = ['JobSatisfaction', 'EnvironmentSatisfaction', 'RelationshipSatisfaction', 'WorkLifeBalance']
display(df.groupby('Attrition')[satisfaction_columns].mean().round(2))

,JobSatisfaction,EnvironmentSatisfaction,RelationshipSatisfaction,WorkLifeBalance
Attrition,,,,
No,2.78,2.77,2.73,2.78
Yes,2.47,2.46,2.60,2.66

## 10. Experience and Tenure Analysis

In [14]:
tenure_columns = ['TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
display(df.groupby('Attrition')[tenure_columns].mean().round(2))

,TotalWorkingYears,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Attrition,,,,,
No,11.86,7.37,4.48,2.23,4.37
Yes,8.24,5.13,2.90,1.95,2.85

## 11. Key Business Insights

- Calculate and document the overall attrition rate.
- Identify departments and job roles with comparatively high attrition.
- Compare attrition between employees who work overtime and those who do not.
- Compare income patterns between employees who stayed and employees who left.
- Examine whether satisfaction and work-life balance differ by attrition status.
- Examine how experience and tenure relate to employee attrition.

**Note:** Final numerical conclusions should be written after running the notebook on the dataset.

## 12. Conclusion

This analysis provides a structured view of employee attrition and workforce characteristics. The findings can support HR teams in identifying patterns related to retention, compensation, workload, satisfaction, and career development.